name: grocery_app
description: A Grocery App MVP

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.2.0
  flutter_snake_navigationbar: ^0.5.0
  get: ^4.1.4
  get_storage: ^2.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  path_provider: ^2.0.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/tab_cart_on.png
    - assets/images/tab_cart_off.png
    - assets/images/tab_explore_on.png
    - assets/images/tab_explore_off.png
    - assets/images/tab_shop_on.png
    - assets/images/tab_shop_off.png
    - assets/images/tab_favorites_on.png
    - assets/images/tab_favorites_off.png
    - assets/images/tab_account_on.png
    - assets/images/tab_account_off.png
    - assets/images/tab_orders_on.png
    - assets/images/tab_orders_off.png
    - assets/images/search_icon.png
    - assets/images/location_icon.png
    - assets/images/logo.png
    - assets/images/add_to_cart_icon.png
    - assets/images/decrease_icon.png
    - assets/images/increase_icon.png
    - assets/images/back_arrow_icon.png
    - assets/images/close_icon.png
    - assets/images/heart_filled_icon.png
    - assets/images/heart_outline_icon.png
    - assets/images/right_arrow_icon.png
    - assets/images/filter_icon.png
    - assets/images/bg.png
    - assets/images/order_success_artwork.png
    - assets/images/status_icon.png
    - assets/images/status_inprogress_icon.png
    - assets/images/logo_splash.png


    #TEMP
    - assets/images/temp/item1.png
    - assets/images/temp/item2.png
    - assets/images/temp/item3.png
    - assets/images/temp/item4.png
    - assets/images/temp/item5.png
    - assets/images/temp/item6.png
    - assets/images/temp/item7.png

    - assets/images/temp/banner.png
    - assets/images/temp/category1.png
    - assets/images/temp/category2.png
    - assets/images/temp/category3.png
    - assets/images/temp/category4.png
    - assets/images/temp/category5.png
    - assets/images/temp/category6.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
